### PR TITLE
Colab notebooks to parse dataset

### PR DESCRIPTION
**Pull request by Favourj-bit**
Using pandas to parse PathwayCommons12.reactome.hgnc.sif.gz dataset on google colab

### CODE REVIEW

**Comment by inoue0426** [comment]
@Favourj-bit Could you attach the colab link to the comment?

**Comment by Favourj-bit** [comment]
@inoue0426 
https://colab.research.google.com/drive/1jY7Y_M6hU84jPtDDO-gRuamTzTxuEK6A?usp=sharing

**Comment by Favourj-bit** [comment]
Created colab notebook to show the parsing of data from cBioPortal (ACC, data_clinical_patient.txt and data_mrna_seq_v2_rsem.txt)
https://colab.research.google.com/drive/16irWREQOMOOSuv-aBWLwUERZ8_gqWu8V?usp=sharing

**Comment by inoue0426** [comment]
@Favourj-bit Do you want me to review this? You can choose to merge this with or without review.

**Pull request merged**
